---
services:
  pg_future:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: future
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: future
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      start_period: 15s
      retries: 5
  future:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./migrations:/migrations
    depends_on:
      pg_future:
        condition: service_healthy
        restart: true
